errors:
    legal_person_format_validation_failed:
      reference: http://example-legal-person-naming-guidence.com
      title: Legal person validation failed
      translation:
        en: Legal person does not match format
        et: Legal person does not match format (et)
        ru: Legal person does not match format (ru)
      type: test-type-for-legal-person-validation
    action_invalid:
      reference: http://example-delegate-not-found-guidence.com
      title: Action is invalid
      translation:
        en: Action is invalid
        et: Action is invalid (et)
        ru: Action is invalid (ru)
      type: test-type-for-action-invalid
    mandate_data_invalid:
      reference: http://example-mandate-data-invalid-guidence.com
      title: Mandate data is invalid
      translation:
        en: Mandate data is invalid
        et: Mandate data is invalid (et)
        ru: Mandate data is invalid (ru)
      type: test-type-for-mandate-data-invalid
    mandate_subdelegate_data_invalid:
      reference: http://example-mandate-subdelegate-data-invalid-guidence.com
      title: Mandate subdelegate data is invalid
      translation:
        en: Mandate subdelegare data is invalid
        et: Mandate subdelegare data is invalid (et)
        ru: Mandate subdelegare data is invalid (ru)
      type: test-type-for-mandate-subdelegate-data-invalid
    mandate_not_found:
      reference: http://example-mandate-not-found-guidence.com
      title: Mandate not found
      translation:
        en: Mandate not found
        et: Mandate not found (et)
        ru: Mandate not found (ru)
      type: test-type-for-mandate-not-found
    internal_server_error:
      reference: http://example-internal-server-error-guidence.com
      title: Internal server error
      translation:
        en: Internal server error
        et: Internal server error (et)
        ru: Internal server error (ru)
      type: test-type-for-internal-server-error-found
    unprocessable_request:
      reference: http://example-unprocessable-request-error-guidence.com
      title: Unprocessable request error
      translation:
        en: Unprocessable request error
        et: Unprocessable request error (et)
        ru: Unprocessable request error (ru)
      type: test-type-for-internal-server-error-found
